base: 'https://typo3v13.ddev.site/'
languages:
  -
    title: Deutsch
    enabled: true
    languageId: 0
    base: /
    locale: de_DE
    navigationTitle: English
    flag: de
    hreflang: ''
    websiteTitle: ''
rootPageId: 1
websiteTitle: ''
