base: 'https://typo3v13.ddev.site/'
baseVariants:
  -
    base: 'https://typo3v13.ddev.site/'
    condition: 'applicationContext == "development"'
  -
    base: 'https://p679284.webspaceconfig.de/'
    condition: 'applicationContext == "Production"'
languages:
  -
    title: Deutsch
    enabled: true
    languageId: 0
    base: /
    locale: de_DE
    navigationTitle: English
    flag: de
    hreflang: ''
    websiteTitle: ''
rootPageId: 1
websiteTitle: ''
